export enum Status {
    KLAR_FOR_INNSENDING = 'KLAR_FOR_INNSENDING',
    FOR_TIDLIG = 'FOR_TIDLIG',
    SENDT_KRAV = 'SENDT_KRAV',
    UTBETALT = 'UTBETALT',
    UTGÅTT = 'UTGÅTT',
    ANNULLERT = 'ANNULLERT',
}
